openapi: 3.1.0
info:
  title: Java API For Lagalt
  description: Api file for the case Lagalt to be used in Insomnia
  version: 1.0.0
  contact:
    name: Lagalt
servers:
  - url: http://localhost:4000
tags:
  - name: users
paths:
  /users:
    post:
      tags:
        - users
      summary: Create a user
      description: Create a new user account
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: Successfully created a new user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    get:
      tags:
        - users
      summary: Get all users
      description: Get a list of all users
      operationId: getUsers
      responses:
        '200':
          description: A list of all users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllUsersResponse'

  /users/{userId}:
    get:
      tags:
        - users
      summary: Get a user by id
      description: Get a user by id
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: The ID of the user
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    CreateUserRequest:
      type: object
      required: [ email, password ]
      properties:
        email:
          type: string
          example: "chris@hello.com"
        password:
          type: string
          example: "password"

    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: "chris@hello.com"
        password:
          type: string
          example: "password"

    AllUsersResponse:
      type: array
      items:
        $ref: '#/components/schemas/User'